#!/bin/bash
#
# mPaste        Startup script for mpaste.
#
# chkconfig: 2345 95 5
# description: mPaste - a lean, mean and clean, pastebinnin' machine.
# pidfile: /var/run/mpaste.pid

### BEGIN INIT INFO
# Provides: mpaste
# Required-Start: $local_fs $network
# Required-Stop: $local_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: A pastebin
# Description: mPaste - a lean, mean pastebinnin' machine.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

RETVAL=0
PIDFILE=/var/run/mpaste.pid

prog=mpaste
exec=/usr/bin/hypnotoad
lockfile=/var/lock/subsys/$prog

# Source config
if [ -f /etc/sysconfig/$prog ] ; then
  . /etc/sysconfig/$prog
fi

start() {
  cd /usr/local/mpaste

  umask 077

  echo -n $"Starting mpaste: "
  hypnotoad ./mpasted
  RETVAL=$?
  echo

  [ $RETVAL -eq 0 ] && touch $lockfile
  return $RETVAL
}

stop() {
  echo -n $"Shutting down mpaste: "
  killproc -p "$PIDFILE" $exec
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && rm -f $lockfile
  return $RETVAL
}

rhstatus() {
        status -p "$PIDFILE" -l $prog $exec
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    rhstatus
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 3
esac

exit $?

